import type { QueryClient } from "@tanstack/react-query";
import type { ApiClient } from "../api/client";
import type { ListParams, ThreadListParams, ReplyListParams, CommunitySearchParams } from "./types";
export declare function createCommunityHooks({ api, queryClient: _qc, }: {
    api: ApiClient;
    queryClient: QueryClient;
}): {
    useContainers: (params?: ListParams) => any;
    useContainer: (containerId: string) => any;
    useCreateContainer: () => any;
    useUpdateContainer: () => any;
    useDeleteContainer: () => any;
    useContainerThreads: ({ containerId, ...params }: ThreadListParams) => any;
    useContainerThread: (threadId: string) => any;
    useCreateThread: () => any;
    useUpdateThread: () => any;
    useDeleteThread: () => any;
    usePublishThread: () => any;
    useLockThread: () => any;
    usePinThread: () => any;
    useUnpinThread: () => any;
    useThreadReplies: ({ threadId, ...params }: ReplyListParams) => any;
    useReply: (replyId: string) => any;
    useCreateReply: () => any;
    useUpdateReply: () => any;
    useDeleteReply: () => any;
    useThreadReactions: (threadId: string) => any;
    useReplyReactions: (replyId: string) => any;
    useAddThreadReaction: () => any;
    useRemoveThreadReaction: () => any;
    useAddReplyReaction: () => any;
    useRemoveReplyReaction: () => any;
    useContainerMembers: (containerId: string, params?: ListParams) => any;
    useContainerModerators: (containerId: string, params?: ListParams) => any;
    useContainerOwners: (containerId: string, params?: ListParams) => any;
    useAddMember: () => any;
    useRemoveMember: () => any;
    useAssignModerator: () => any;
    useRemoveModerator: () => any;
    useAssignOwner: () => any;
    useRemoveOwner: () => any;
    useNotifications: (params?: ListParams) => any;
    useNotificationsUnreadCount: () => any;
    useMarkNotificationRead: () => any;
    useMarkAllNotificationsRead: () => any;
    useReports: (params?: ListParams) => any;
    useReport: (reportId: string) => any;
    useCreateReport: () => any;
    useResolveReport: () => any;
    useDismissReport: () => any;
    useBans: (params?: ListParams) => any;
    useCheckBan: (userId: string, containerId?: string) => any;
    useCreateBan: () => any;
    useRemoveBan: () => any;
    useSearchThreads: (params: CommunitySearchParams & {
        q: string;
    }) => any;
    useSearchReplies: (params: CommunitySearchParams & {
        q: string;
    }) => any;
};
export type CommunityHooks = ReturnType<typeof createCommunityHooks>;
