import type { FrontendManifest } from "../manifest/schema";

/**
 * Generates the app entry file with:
 * - Exported registries (componentRegistry, manifestRegistry) for consumer extension
 * - AppRoot that wraps QueryClientProvider + RendererProvider + RouterProvider
 * - configure() pre-render hook for custom guards, components, and layouts
 */
export function generateAppEntry(manifest: FrontendManifest): string {
  const hasRoles = Object.values(manifest.pages).some((p) => p.roles && p.roles.length > 0);
  const hasGuards = Object.values(manifest.pages).some((p) => !!p.guard);

  return `// Generated by @lastshotlabs/snapshot. Do not edit manually.
import { createDefaultRegistry, RendererProvider, usePageContextAccessors } from "@lastshotlabs/snapshot/components"
import { createDefaultManifestRegistry } from "@lastshotlabs/snapshot/manifest"
import type { RendererContext } from "@lastshotlabs/snapshot/components"
import type { ComponentRegistry } from "@lastshotlabs/snapshot/components"
import type { ManifestHandlerRegistry } from "@lastshotlabs/snapshot/manifest"
import { app } from "./snapshot.config"
import { createAppRouter } from "./routeTree.gen"
import { RouterProvider } from "@tanstack/react-router"
import { QueryClientProvider } from "@tanstack/react-query"
import { useMemo } from "react"

// ── Registries (exported for consumer extension) ─────────────────────────────
// Extend these BEFORE rendering AppRoot:
//
//   import { componentRegistry, manifestRegistry } from "./generated/app"
//   componentRegistry.register("kanban", KanbanComponent, kanbanSchema)
//   manifestRegistry.register("guard", "admin-only", () => adminGuardFn)

export const componentRegistry: ComponentRegistry = createDefaultRegistry()
export const manifestRegistry: ManifestHandlerRegistry = createDefaultManifestRegistry()

// ── Router context (guard-only — works outside React render) ─────────────────

export interface AppRouterContext {
  queryClient: typeof app.queryClient
  protectedBeforeLoad: typeof app.protectedBeforeLoad
  guestBeforeLoad: typeof app.guestBeforeLoad${hasRoles ? "\n  getUserRoles: () => string[]" : ""}${hasRoles ? "\n  forbiddenPath: string" : ""}${hasGuards ? "\n  resolveGuard: (name: string) => (ctx: { context: AppRouterContext }) => Promise<void>" : ""}
}

const routerContext: AppRouterContext = {
  queryClient: app.queryClient,
  protectedBeforeLoad: app.protectedBeforeLoad,
  guestBeforeLoad: app.guestBeforeLoad,${
    hasRoles
      ? `
  getUserRoles: () => {
    const user = app.queryClient.getQueryData<{ roles?: string[] }>(["auth", "me"])
    return user?.roles ?? []
  },
  forbiddenPath: "${manifest.auth?.forbiddenPath ?? "/403"}",`
      : ""
  }${
    hasGuards
      ? `
  resolveGuard: (name: string) => {
    return async ({ context }: { context: AppRouterContext }) => {
      if (name === "authenticated") return context.protectedBeforeLoad({ context })
      if (name === "guest") return context.guestBeforeLoad({ context })
      // Resolve custom guard from the exported manifestRegistry
      if (manifestRegistry.has("guard", name)) {
        const guardFn = manifestRegistry.resolve<(ctx: { context: AppRouterContext }) => Promise<void>>("guard", name)
        return guardFn({ context })
      }
      return context.protectedBeforeLoad({ context })
    }
  },`
      : ""
  }
}

export const router = createAppRouter(routerContext)

// ── App root component ───────────────────────────────────────────────────────

export function AppRoot() {
  const { getPageValue, setPageValue, openModal, closeModal } = usePageContextAccessors()

  const rendererContext: RendererContext = useMemo(() => ({
    registry: componentRegistry,
    api: app.api,
    actionContext: {
      api: app.api,
      queryClient: app.queryClient,
      navigate: (to: string) => router.navigate({ to }),
      openModal,
      closeModal,
      setPageValue,
      getPageValue,
      showToast: (message: string, type?: string) => {
        if (type === "error") console.error("[toast]", message)
        else console.log("[toast]", message)
      },
    },
  }), [getPageValue, setPageValue, openModal, closeModal])

  return (
    <QueryClientProvider client={app.queryClient}>
      <RendererProvider context={rendererContext}>
        <RouterProvider router={router} />
      </RendererProvider>
    </QueryClientProvider>
  )
}

export { app }

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}
`;
}
