import type { FrontendManifest, PageConfig } from "../manifest/schema";

/**
 * Generates React page component files from the manifest's page definitions.
 *
 * Each page:
 * - Reads rendererContext from RendererProvider (hook-backed action methods)
 * - Resolves page layout from the component registry (sidebar, topnav, etc.)
 * - Passes full page config to ComponentTreeRenderer
 *
 * @returns Record<filename, sourceCode>
 */
export function generatePages(manifest: FrontendManifest): Record<string, string> {
  const files: Record<string, string> = {};

  for (const [path, page] of Object.entries(manifest.pages)) {
    const filename = pathToFilename(path);
    files[`pages/${filename}.tsx`] = generatePageComponent(path, page);
  }

  return files;
}

function pathToFilename(path: string): string {
  if (path === "/") return "index";
  return path
    .replace(/^\//, "")
    .replace(/\//g, ".")
    .replace(/:(\w+)/g, "$$$1")
    .replace(/[^a-zA-Z0-9.$]/g, "-");
}

function pathToComponentName(path: string): string {
  if (path === "/") return "IndexPage";
  const parts = path
    .replace(/^\//, "")
    .split("/")
    .map((seg) => {
      if (seg.startsWith(":")) return seg.slice(1).charAt(0).toUpperCase() + seg.slice(2);
      return seg.charAt(0).toUpperCase() + seg.slice(1);
    });
  return parts.join("") + "Page";
}

/** Map manifest layout names to component registry names. */
const layoutComponentMap: Record<string, string> = {
  sidebar: "sidebar-layout",
  topnav: "topnav-layout",
  full: "full-layout",
  split: "split-layout",
};

function generatePageComponent(path: string, page: PageConfig): string {
  const componentName = pathToComponentName(path);
  const configJson = JSON.stringify(page.components, null, 2);
  const layout = typeof page.layout === "string" ? page.layout : null;
  const layoutHandlerRef =
    typeof page.layout === "object" && page.layout !== null
      ? (page.layout as { handler: string }).handler
      : null;

  // Determine if this page uses a layout component
  const layoutComponentType =
    layoutHandlerRef ?? (layout ? (layoutComponentMap[layout] ?? `${layout}-layout`) : null);

  if (layoutComponentType) {
    // Page with layout — resolve layout from component registry at runtime
    return `// Generated by @lastshotlabs/snapshot. Do not edit manually.

import { ComponentTreeRenderer, ComponentRenderer, useRendererContext } from "@lastshotlabs/snapshot/components"

const components = ${configJson}

export function ${componentName}() {
  const context = useRendererContext()
  const layoutEntry = context.registry.resolve("${layoutComponentType}")

  // If layout component is registered, wrap page content with it
  if (layoutEntry) {
    const Layout = layoutEntry.component
    return (
      <Layout config={{ type: "${layoutComponentType}" }}>
${page.title ? `        <h1>${page.title}</h1>\n` : ""}        <ComponentTreeRenderer configs={components} context={context} />
      </Layout>
    )
  }

  // Fallback: render without layout wrapper
  return (
    <div>
${page.title ? `      <h1>${page.title}</h1>\n` : ""}      <ComponentTreeRenderer configs={components} context={context} />
    </div>
  )
}
`;
  }

  // Page without layout
  return `// Generated by @lastshotlabs/snapshot. Do not edit manually.

import { ComponentTreeRenderer, useRendererContext } from "@lastshotlabs/snapshot/components"

const components = ${configJson}

export function ${componentName}() {
  const context = useRendererContext()

  return (
    <div>
${page.title ? `      <h1>${page.title}</h1>\n` : ""}      <ComponentTreeRenderer configs={components} context={context} />
    </div>
  )
}
`;
}
