import type { FrontendManifest, PageConfig } from "../manifest/schema";

/**
 * Generates React page component files from the manifest's page definitions.
 *
 * Each page:
 * - Reads `rendererContext` from the TanStack Router route context (provided by the app entry)
 * - Passes the full page config to `ComponentTreeRenderer`
 * - All manifest behavior (columns, actions, data binding, pagination, etc.) round-trips correctly
 *
 * @returns Record<filename, sourceCode>
 */
export function generatePages(manifest: FrontendManifest): Record<string, string> {
  const files: Record<string, string> = {};

  for (const [path, page] of Object.entries(manifest.pages)) {
    const filename = pathToFilename(path);
    files[`pages/${filename}.tsx`] = generatePageComponent(path, page);
  }

  return files;
}

function pathToFilename(path: string): string {
  if (path === "/") return "index";
  return path
    .replace(/^\//, "")
    .replace(/\//g, ".")
    .replace(/:(\w+)/g, "$$$1")
    .replace(/[^a-zA-Z0-9.$]/g, "-");
}

function pathToComponentName(path: string): string {
  if (path === "/") return "IndexPage";
  const parts = path
    .replace(/^\//, "")
    .split("/")
    .map((seg) => {
      if (seg.startsWith(":")) return seg.slice(1).charAt(0).toUpperCase() + seg.slice(2);
      return seg.charAt(0).toUpperCase() + seg.slice(1);
    });
  return parts.join("") + "Page";
}

function generatePageComponent(path: string, page: PageConfig): string {
  const componentName = pathToComponentName(path);
  const configJson = JSON.stringify(page.components, null, 2);
  const layout = typeof page.layout === "string" ? page.layout : undefined;
  const layoutAttr = layout ? ` data-layout="${layout}"` : "";

  // Pages read rendererContext from the RendererProvider — a React context
  // populated by the app root with hook-backed action methods.
  return `// Generated by @lastshotlabs/snapshot. Do not edit manually.

import { ComponentTreeRenderer, useRendererContext } from "@lastshotlabs/snapshot/components"

const components = ${configJson}

export function ${componentName}() {
  const context = useRendererContext()

  return (
    <div${layoutAttr}>
${page.title ? `      <h1>${page.title}</h1>\n` : ""}      <ComponentTreeRenderer configs={components} context={context} />
    </div>
  )
}
`;
}
