import type { FrontendManifest, PageConfig } from "../manifest/schema";

/**
 * Generates a TanStack Router route tree file from the manifest's page definitions.
 *
 * The generated router expects a context object (provided by the app entry) that includes:
 * - `rendererContext` — for ComponentTreeRenderer in pages
 * - `protectedBeforeLoad` / `guestBeforeLoad` — from the auth plugin
 * - `getUserRoles` — for role-based guards
 * - `forbiddenPath` — redirect target for unauthorized access
 * - `resolveGuard` — for custom manifest guards
 */
export function generateRouteTree(manifest: FrontendManifest): string {
  const pages = Object.keys(manifest.pages).sort();
  const hasRoleProtectedPages = pages.some((p) => {
    const page = manifest.pages[p]!;
    return page.roles && page.roles.length > 0;
  });

  const lines: string[] = [
    "// Generated by @lastshotlabs/snapshot. Do not edit manually.",
    "",
    'import { createRootRouteWithContext, createRoute, createRouter, redirect } from "@tanstack/react-router"',
    'import type { AppRouterContext } from "./app"',
  ];

  // Import page components
  for (const path of pages) {
    const componentName = pathToComponentName(path);
    const filename = pathToFilename(path);
    lines.push(`import { ${componentName} } from "./pages/${filename}"`);
  }

  lines.push("");

  // Role checking helper
  if (hasRoleProtectedPages) {
    lines.push("async function requireRoles(context: AppRouterContext, roles: string[]) {");
    lines.push("  await context.protectedBeforeLoad({ context })");
    lines.push("  const userRoles = context.getUserRoles?.() ?? []");
    lines.push("  const hasRole = roles.some((r) => userRoles.includes(r))");
    lines.push("  if (!hasRole) {");
    lines.push('    throw redirect({ to: context.forbiddenPath ?? "/" })');
    lines.push("  }");
    lines.push("}");
    lines.push("");
  }

  // Root route with typed context
  lines.push("const rootRoute = createRootRouteWithContext<AppRouterContext>()({})");
  lines.push("");

  // Individual routes
  for (const path of pages) {
    const page = manifest.pages[path]!;
    const componentName = pathToComponentName(path);
    const routeVarName = pathToRouteVarName(path);
    const routePath = path === "/" ? "/" : path;
    const beforeLoad = buildBeforeLoad(page);

    lines.push(`const ${routeVarName} = createRoute({`);
    lines.push(`  getParentRoute: () => rootRoute,`);
    lines.push(`  path: "${routePath}",`);
    lines.push(`  component: ${componentName},${beforeLoad}`);
    lines.push(`})`);
    lines.push("");
  }

  // Route tree
  lines.push("const routeTree = rootRoute.addChildren([");
  for (const path of pages) {
    lines.push(`  ${pathToRouteVarName(path)},`);
  }
  lines.push("])");
  lines.push("");

  // Router — created with context from app entry
  lines.push("export function createAppRouter(context: AppRouterContext) {");
  lines.push("  return createRouter({ routeTree, context })");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function buildBeforeLoad(page: PageConfig): string {
  if (page.guard) {
    const guardName = typeof page.guard === "string" ? page.guard : page.guard.handler;

    if (guardName === "authenticated") {
      return `\n  beforeLoad: ({ context }) => context.protectedBeforeLoad({ context }),`;
    }
    if (guardName === "guest") {
      return `\n  beforeLoad: ({ context }) => context.guestBeforeLoad({ context }),`;
    }
    return `\n  beforeLoad: ({ context }) => context.resolveGuard("${guardName}")({ context }),`;
  }

  if (page.roles && page.roles.length > 0) {
    const rolesJson = JSON.stringify(page.roles);
    return `\n  beforeLoad: ({ context }) => requireRoles(context, ${rolesJson}),`;
  }

  return "";
}

function pathToFilename(path: string): string {
  if (path === "/") return "index";
  return path
    .replace(/^\//, "")
    .replace(/\//g, ".")
    .replace(/:(\w+)/g, "$$$1")
    .replace(/[^a-zA-Z0-9.$]/g, "-");
}

function pathToComponentName(path: string): string {
  if (path === "/") return "IndexPage";
  const parts = path
    .replace(/^\//, "")
    .split("/")
    .map((seg) => {
      if (seg.startsWith(":")) return seg.slice(1).charAt(0).toUpperCase() + seg.slice(2);
      return seg.charAt(0).toUpperCase() + seg.slice(1);
    });
  return parts.join("") + "Page";
}

function pathToRouteVarName(path: string): string {
  if (path === "/") return "indexRoute";
  const name = path
    .replace(/^\//, "")
    .replace(/\//g, "_")
    .replace(/:(\w+)/g, "$1")
    .replace(/[^a-zA-Z0-9_]/g, "");
  return name + "Route";
}
