import type { FrontendManifest } from "../manifest/schema";
import { createTokens } from "../tokens/presets";
import { resolveTokensToCSS } from "../tokens/resolve";

/**
 * Generates theme CSS from the manifest's theme config.
 *
 * Resolves the manifest's preset + category selections + overrides
 * through the token system, then produces CSS custom properties.
 */
export function generateThemeCSS(manifest: FrontendManifest): string {
  const themeConfig = manifest.theme ?? {};

  const tokens = createTokens({
    preset: themeConfig.preset,
    categories: themeConfig.categories as Record<string, string> | undefined,
    overrides: themeConfig.overrides as Record<string, unknown> | undefined,
  });

  const header = ["/* Generated by @lastshotlabs/snapshot. Do not edit manually. */", ""].join(
    "\n",
  );

  return header + resolveTokensToCSS(tokens);
}
