// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Create board build */
export const postApiBoardBuilds = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>("/api/board-builds", body);

/** Get board build */
export const getApiBoardBuildsById = (
  id: string,
): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(`/api/board-builds/${id}`);

/** Update board build */
export const patchApiBoardBuildsById = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(`/api/board-builds/${id}`, body);

/** Regenerate board build */
export const postApiBoardBuildsByIdRegenerate = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/board-builds/${id}/regenerate`, body);

/** Save board build as clue set */
export const postApiBoardBuildsByIdSaveAsClueSet = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/board-builds/${id}/save-as-clue-set`,
    body,
  );

/** Create match from board build */
export const postApiBoardBuildsByIdCreateMatch = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/board-builds/${id}/create-match`, body);
