// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Discover published content */
export const getApiDiscovery = (
  q?: string,
  kind?: string,
  scopeKind?: string,
  language?: string,
  visibility?: string,
  owner?: string,
  ownerUserId?: string,
  publicationStatus?: string,
  workflowStatus?: string,
  moderationStatus?: string,
  difficulty?: string,
  ratingMin?: string,
  rating?: string,
  tags?: string,
  tag?: string,
  includeModeration?: string,
): Promise<JeopardyApiJsonObject> => {
  const _q = new URLSearchParams();
  if (q != null) _q.set("q", String(q));
  if (kind != null) _q.set("kind", String(kind));
  if (scopeKind != null) _q.set("scopeKind", String(scopeKind));
  if (language != null) _q.set("language", String(language));
  if (visibility != null) _q.set("visibility", String(visibility));
  if (owner != null) _q.set("owner", String(owner));
  if (ownerUserId != null) _q.set("ownerUserId", String(ownerUserId));
  if (publicationStatus != null)
    _q.set("publicationStatus", String(publicationStatus));
  if (workflowStatus != null) _q.set("workflowStatus", String(workflowStatus));
  if (moderationStatus != null)
    _q.set("moderationStatus", String(moderationStatus));
  if (difficulty != null) _q.set("difficulty", String(difficulty));
  if (ratingMin != null) _q.set("ratingMin", String(ratingMin));
  if (rating != null) _q.set("rating", String(rating));
  if (tags != null) _q.set("tags", String(tags));
  if (tag != null) _q.set("tag", String(tag));
  if (includeModeration != null)
    _q.set("includeModeration", String(includeModeration));
  return api.get<JeopardyApiJsonObject>(`/api/discovery?${_q}`);
};

/** Rate content */
export const postApiDiscoveryByKindByIdRating = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/discovery/${kind}/${id}/rating`, body);

/** Save content preference */
export const postApiDiscoveryByKindByIdPreferences = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/discovery/${kind}/${id}/preferences`,
    body,
  );
