// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiGuestSessionResponse,
  JeopardyApiOkResponse,
} from "../types/api";

/** Create guest session */
export const postApiGuestSession = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiGuestSessionResponse> =>
  api.post<JeopardyApiGuestSessionResponse>("/api/guest/session", body);

/** Revoke guest session */
export const deleteApiGuestSession = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiOkResponse> =>
  api.delete<JeopardyApiOkResponse>("/api/guest/session", body);
