// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Import library JSON */
export const postApiImportsLibraryJson = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>("/api/imports/library/json", body);

/** Import library CSV */
export const postApiImportsLibraryCsv = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>("/api/imports/library/csv", body);

/** Export library record as JSON */
export const postApiExportsLibraryByKindByIdJson = (
  kind: string,
  id: string,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/exports/library/${kind}/${id}/json`,
    undefined,
  );
