// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** List library records */
export const getApiLibraryByKind = (
  kind: string,
  workflowStatus?: string,
  scopeKind?: string,
  visibility?: string,
  q?: string,
): Promise<JeopardyApiItemsResponse> => {
  const _q = new URLSearchParams();
  if (workflowStatus != null) _q.set("workflowStatus", String(workflowStatus));
  if (scopeKind != null) _q.set("scopeKind", String(scopeKind));
  if (visibility != null) _q.set("visibility", String(visibility));
  if (q != null) _q.set("q", String(q));
  return api.get<JeopardyApiItemsResponse>(`/api/library/${kind}?${_q}`);
};

/** Create library record */
export const postApiLibraryByKind = (
  kind: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}`, body);

/** Get library record */
export const getApiLibraryByKindById = (
  kind: string,
  id: string,
): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(`/api/library/${kind}/${id}`);

/** Update library record */
export const patchApiLibraryByKindById = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(`/api/library/${kind}/${id}`, body);

/** List library versions */
export const getApiLibraryByKindByIdVersions = (
  kind: string,
  id: string,
): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/versions`);

/** Create library version */
export const postApiLibraryByKindByIdVersions = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/versions`, body);

/** Get library version */
export const getApiLibraryByKindByIdVersionsByVersionId = (
  kind: string,
  id: string,
  versionId: string,
): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(
    `/api/library/${kind}/${id}/versions/${versionId}`,
  );

/** Submit library record */
export const postApiLibraryByKindByIdSubmit = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/submit`, body);

/** Approve library record */
export const postApiLibraryByKindByIdApprove = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/approve`, body);

/** Reject library record */
export const postApiLibraryByKindByIdReject = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/reject`, body);

/** Publish library record */
export const postApiLibraryByKindByIdPublish = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/publish`, body);

/** Archive library record */
export const postApiLibraryByKindByIdArchive = (
  kind: string,
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/library/${kind}/${id}/archive`, body);
