// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** List matches */
export const getApiMatches = (
  hostUserId?: string,
  status?: string,
  visibility?: string,
): Promise<JeopardyApiItemsResponse> => {
  const _q = new URLSearchParams();
  if (hostUserId != null) _q.set("hostUserId", String(hostUserId));
  if (status != null) _q.set("status", String(status));
  if (visibility != null) _q.set("visibility", String(visibility));
  return api.get<JeopardyApiItemsResponse>(`/api/matches?${_q}`);
};

/** Create match */
export const postApiMatches = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>("/api/matches", body);

/** Get match */
export const getApiMatchesById = (id: string): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(`/api/matches/${id}`);

/** Get match state */
export const getApiMatchesByIdState = (
  id: string,
): Promise<JeopardyApiJsonObject> =>
  api.get<JeopardyApiJsonObject>(`/api/matches/${id}/state`);

/** Start match */
export const postApiMatchesByIdStart = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/start`, body);

/** Pause match */
export const postApiMatchesByIdPause = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/pause`, body);

/** Resume match */
export const postApiMatchesByIdResume = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/resume`, body);

/** End match */
export const postApiMatchesByIdEnd = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/end`, body);

/** Evaluate answer submission */
export const postApiMatchesByIdEvaluateAnswer = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/evaluate-answer`, body);
