// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** Join match */
export const postApiMatchesByIdJoin = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/join`, body);

/** List match access entries */
export const getApiMatchesByIdAccess = (
  id: string,
): Promise<JeopardyApiItemsResponse> =>
  api.get<JeopardyApiItemsResponse>(`/api/matches/${id}/access`);

/** Request to join match */
export const postApiMatchesByIdRequestJoin = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/request-join`, body);

/** Request to join match */
export const postApiMatchesByIdAccessRequestJoin = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/access/request-join`,
    body,
  );

/** Approve match access entry */
export const postApiMatchesByIdApproveByEntryId = (
  id: string,
  entryId: string,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/approve/${entryId}`,
    undefined,
  );

/** Approve match access entry */
export const postApiMatchesByIdAccessApproveByEntryId = (
  id: string,
  entryId: string,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/access/approve/${entryId}`,
    undefined,
  );

/** Promote waitlist entry */
export const postApiMatchesByIdWaitlistByEntryIdPromote = (
  id: string,
  entryId: string,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/waitlist/${entryId}/promote`,
    undefined,
  );

/** Create reservation */
export const postApiMatchesByIdReservations = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/reservations`, body);

/** Create reservation */
export const postApiMatchesByIdAccessReservations = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/access/reservations`,
    body,
  );

/** Create invite */
export const postApiMatchesByIdInvites = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/invites`, body);

/** Create invite */
export const postApiMatchesByIdAccessInvites = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/access/invites`, body);

/** Ban access entry */
export const postApiMatchesByIdBanByEntryId = (
  id: string,
  entryId: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/ban/${entryId}`, body);

/** Create ban entry */
export const postApiMatchesByIdAccessBan = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/access/ban`, body);
