// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Get match replay */
export const getApiMatchesByIdReplay = (
  id: string,
  audience?: string,
  includeReplay?: string,
): Promise<JeopardyApiJsonObject> => {
  const _q = new URLSearchParams();
  if (audience != null) _q.set("audience", String(audience));
  if (includeReplay != null) _q.set("includeReplay", String(includeReplay));
  return api.get<JeopardyApiJsonObject>(`/api/matches/${id}/replay?${_q}`);
};

/** Export replay payload */
export const postApiExportsMatchesByIdReplay = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/exports/matches/${id}/replay`, body);

/** Export match bundle */
export const getApiMatchesByIdExportJson = (
  id: string,
  audience?: string,
  includeReplay?: string,
): Promise<JeopardyApiJsonObject> => {
  const _q = new URLSearchParams();
  if (audience != null) _q.set("audience", String(audience));
  if (includeReplay != null) _q.set("includeReplay", String(includeReplay));
  return api.get<JeopardyApiJsonObject>(`/api/matches/${id}/export/json?${_q}`);
};
