// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Create host-controlled player seat */
export const postApiMatchesByIdHostPlayers = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host-players`, body);

/** Update player */
export const patchApiMatchesByIdPlayersByPlayerId = (
  id: string,
  playerId: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(
    `/api/matches/${id}/players/${playerId}`,
    body,
  );

/** Replace player seat binding */
export const postApiMatchesByIdPlayersByPlayerIdReplace = (
  id: string,
  playerId: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/players/${playerId}/replace`,
    body,
  );

/** Update player team */
export const patchApiMatchesByIdPlayersByPlayerIdTeam = (
  id: string,
  playerId: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(
    `/api/matches/${id}/players/${playerId}/team`,
    body,
  );

/** Update player role */
export const patchApiMatchesByIdPlayersByPlayerIdRole = (
  id: string,
  playerId: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(
    `/api/matches/${id}/players/${playerId}/role`,
    body,
  );
