// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Host action advance */
export const postApiMatchesByIdHostAdvance = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/advance`, body);

/** Host action select-buzz-winner */
export const postApiMatchesByIdHostSelectBuzzWinner = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/host/select-buzz-winner`,
    body,
  );

/** Host action select-clue */
export const postApiMatchesByIdHostSelectClue = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/select-clue`, body);

/** Host action designate-responder */
export const postApiMatchesByIdHostDesignateResponder = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/host/designate-responder`,
    body,
  );

/** Host action reveal-media */
export const postApiMatchesByIdHostRevealMedia = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/reveal-media`, body);

/** Host action judge-attempt */
export const postApiMatchesByIdHostJudgeAttempt = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/host/judge-attempt`,
    body,
  );

/** Host action reopen-buzz */
export const postApiMatchesByIdHostReopenBuzz = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/reopen-buzz`, body);

/** Host action kill-clue */
export const postApiMatchesByIdHostKillClue = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/kill-clue`, body);

/** Host action score-adjust */
export const postApiMatchesByIdHostScoreAdjust = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/score-adjust`, body);

/** Host action patch-board */
export const postApiMatchesByIdHostPatchBoard = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/matches/${id}/host/patch-board`, body);

/** Host action save-board-fix */
export const postApiMatchesByIdHostSaveBoardFix = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(
    `/api/matches/${id}/host/save-board-fix`,
    body,
  );

/** Patch match board snapshot */
export const patchApiMatchesByIdHostBoard = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.patch<JeopardyApiJsonObject>(`/api/matches/${id}/host/board`, body);
