// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** Create moderation report */
export const postApiModerationReports = (
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>("/api/moderation/reports", body);

/** List moderation cases */
export const getApiModerationCases = (
  status?: string,
): Promise<JeopardyApiItemsResponse> => {
  const _q = new URLSearchParams();
  if (status != null) _q.set("status", String(status));
  return api.get<JeopardyApiItemsResponse>(`/api/moderation/cases?${_q}`);
};

/** Create moderation action */
export const postApiModerationCasesByIdActions = (
  id: string,
  body: JeopardyApiAnyJsonBody,
): Promise<JeopardyApiJsonObject> =>
  api.post<JeopardyApiJsonObject>(`/api/moderation/cases/${id}/actions`, body);
