// Generated by bunx snapshot sync. Do not edit manually.

import { api } from "@lib/snapshot";
import type {
  JeopardyApiHealthResponse,
  JeopardyApiReadyResponse,
  JeopardyApiStatusResponse,
} from "../types/api";

/** Health check */
export const getApiHealth = (): Promise<JeopardyApiHealthResponse> =>
  api.get<JeopardyApiHealthResponse>("/api/health");

/** Readiness check */
export const getApiReady = (): Promise<JeopardyApiReadyResponse> =>
  api.get<JeopardyApiReadyResponse>("/api/ready");

/** Runtime status */
export const getApiJeopardyStatus = (): Promise<JeopardyApiStatusResponse> =>
  api.get<JeopardyApiStatusResponse>("/api/jeopardy/status");
