// src/cli/templates/ssr-entry-client.ts
// Template for SSR client hydration entry.

/**
 * Generate the SSR client hydration entry file content.
 *
 * Reads the dehydrated QueryClient state injected by the SSR renderer,
 * creates a client QueryClient, and calls `hydrateRoot` with the full
 * provider tree.
 *
 * @returns The complete file content as a string.
 */
export function ssrEntryClientTemplate(): string {
  return `// src/ssr/entry-client.tsx
// AUTO-GENERATED by \`snapshot init --ssr\` — do not edit manually.
// Regenerate: bun run snapshot init --ssr
import { HydrationBoundary, QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import React from 'react';
import { hydrateRoot } from 'react-dom/client';
import { routeTree } from '../routeTree.gen';

// Read dehydrated state injected by the SSR renderer
const stateEl = document.getElementById('__SNAPSHOT_QUERY_STATE__');
const dehydratedState = stateEl ? JSON.parse(stateEl.textContent!) : null;

const queryClient = new QueryClient({
  defaultOptions: { queries: { staleTime: 30_000 } },
});

const router = createRouter({ routeTree, context: { queryClient } });

hydrateRoot(
  document.getElementById('root')!,
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <HydrationBoundary state={dehydratedState}>
        <RouterProvider router={router} />
      </HydrationBoundary>
    </QueryClientProvider>
  </React.StrictMode>,
);
`;
}
