// src/cli/templates/ssr-entry-server.ts
// Template for SSR server bundle entry.

/**
 * Generate the SSR server bundle entry file content.
 *
 * This file is the entry point for the Vite SSR build. It re-exports the
 * renderer factory so the server bundle exposes `createReactRenderer`.
 *
 * @returns The complete file content as a string.
 */
export function ssrEntryServerTemplate(): string {
  return `// src/ssr/entry-server.ts
// AUTO-GENERATED by \`snapshot init --ssr\` — do not edit manually.
// Regenerate: bun run snapshot init --ssr
export { createReactRenderer } from '@lastshotlabs/snapshot/ssr';
`;
}
