// src/cli/templates/ssr-entry-worker.ts
// Template for the Cloudflare Workers SSR entry point.

/**
 * Generate the Cloudflare Workers SSR entry file content.
 *
 * The generated file exports a standard CF Workers `fetch` handler that:
 * 1. Creates a Slingshot app on each request using `edgeRuntime()`.
 * 2. Wires `env.ASSETS` as the file store so `runtime.readFile()` fetches
 *    bundled static assets from the Workers Assets binding.
 * 3. Optionally attaches a KV-backed ISR cache via `env.ISR_CACHE`.
 * 4. Delegates the request to the Slingshot SSR plugin.
 *
 * The template is a pure function — it only returns a string. All filesystem
 * writes are the scaffold layer's responsibility (per snapshot CLAUDE.md rule 13).
 *
 * @returns The complete file content as a string.
 */
export function ssrEntryWorkerTemplate(): string {
  return `// src/ssr/entry-worker.ts
// AUTO-GENERATED by \`snapshot init --edge\` — do not edit manually.
// Regenerate: bun run snapshot init --edge
import { createApp } from 'slingshot';
import { createSsrPlugin } from '@lastshotlabs/slingshot-ssr';
import { createReactRenderer } from '@lastshotlabs/snapshot/ssr';
import { edgeRuntime } from '@lastshotlabs/runtime-edge';
import { createKvIsrCache } from '@lastshotlabs/runtime-edge/kv';
import type { IsrCacheAdapter } from '@lastshotlabs/slingshot-ssr';

// Vite inlines the manifest at build time via the edge-cloudflare target.
// The import assertion ensures Vite treats the JSON as a static asset.
import clientManifest from '../dist/client/.vite/manifest.json' with { type: 'json' };

// --- section:env ---
/**
 * Cloudflare Workers environment bindings.
 * Update this interface to match your wrangler.toml \`[[kv_namespaces]]\` and
 * \`[assets]\` configuration.
 */
interface Env {
  /**
   * Workers Assets binding for serving client-side static files.
   * Configure in wrangler.toml: \`[assets]\` / \`directory = "./dist/client"\`
   */
  ASSETS: { fetch(url: string | Request): Promise<Response> };
  /**
   * KV namespace for ISR page caching.
   * Configure in wrangler.toml: \`[[kv_namespaces]]\` / \`binding = "ISR_CACHE"\`
   * Optional — ISR is disabled when this binding is not configured.
   */
  ISR_CACHE?: KVNamespace;
}
// --- end:env ---

// --- section:fetch ---
export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const isrAdapter: IsrCacheAdapter | undefined = env.ISR_CACHE
      ? createKvIsrCache(env.ISR_CACHE)
      : undefined;

    const app = await createApp({
      runtime: edgeRuntime({
        // Read bundled static assets from the Workers Assets binding.
        // Falls back to null for paths not in the asset bundle.
        fileStore: async (path: string) => {
          const url = new URL(path, request.url).toString();
          const res = await env.ASSETS.fetch(url);
          return res.ok ? res.text() : null;
        },
      }),
      plugins: [
        createSsrPlugin({
          renderer: createReactRenderer({ resolveComponent }),
          // Asset manifest is inlined at build time — no filesystem read at runtime.
          assetsManifest: JSON.stringify(clientManifest),
          isr: isrAdapter ? { adapter: isrAdapter } : undefined,
        }),
      ],
    });

    return app.fetch(request);
  },
};
// --- end:fetch ---

// --- section:resolve-component ---
import type { SsrRouteMatch } from '@lastshotlabs/slingshot-ssr';

/**
 * Resolve a server route match to its React page component.
 *
 * Replace the placeholder \`import()\` below with your actual page component
 * imports. The \`match.filePath\` is the absolute path to the route file.
 *
 * @example
 * \`\`\`ts
 * async function resolveComponent(match: SsrRouteMatch) {
 *   if (match.filePath.endsWith('posts/[slug].ts')) {
 *     const { default: PostPage } = await import('./pages/PostPage');
 *     return PostPage;
 *   }
 *   return null;
 * }
 * \`\`\`
 */
async function resolveComponent(match: SsrRouteMatch): Promise<unknown> {
  // TODO: Import your page components here.
  // Vite's code-splitting will create separate chunks for each dynamic import.
  throw new Error(
    \`[entry-worker] No component registered for route: \${match.filePath}. \` +
      'Update resolveComponent() in src/ssr/entry-worker.ts.',
  );
}
// --- end:resolve-component ---
`.trim();
}
