// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  postApiBoardBuilds,
  getApiBoardBuildsById,
  patchApiBoardBuildsById,
  postApiBoardBuildsByIdRegenerate,
  postApiBoardBuildsByIdSaveAsClueSet,
  postApiBoardBuildsByIdCreateMatch,
} from "../api/board-builds";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Create board build */
export function usePostApiBoardBuildsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiBoardBuilds,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Get board build */
export function useGetApiBoardBuildsByIdQuery(
  params: { id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "board-builds", params.id],
    queryFn: () => getApiBoardBuildsById(params.id),
    ...options,
  });
}

/** Update board build */
export function usePatchApiBoardBuildsByIdMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => patchApiBoardBuildsById(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Regenerate board build */
export function usePostApiBoardBuildsByIdRegenerateMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiBoardBuildsByIdRegenerate(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Save board build as clue set */
export function usePostApiBoardBuildsByIdSaveAsClueSetMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiBoardBuildsByIdSaveAsClueSet(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create match from board build */
export function usePostApiBoardBuildsByIdCreateMatchMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiBoardBuildsByIdCreateMatch(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
