// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  getApiDiscovery,
  postApiDiscoveryByKindByIdRating,
  postApiDiscoveryByKindByIdPreferences,
} from "../api/discovery";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Discover published content */
export function useGetApiDiscoveryQuery(
  params: {
    q?: string;
    kind?: string;
    scopeKind?: string;
    language?: string;
    visibility?: string;
    owner?: string;
    ownerUserId?: string;
    publicationStatus?: string;
    workflowStatus?: string;
    moderationStatus?: string;
    difficulty?: string;
    ratingMin?: string;
    rating?: string;
    tags?: string;
    tag?: string;
    includeModeration?: string;
  } = {},
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "discovery",
      params.q,
      params.kind,
      params.scopeKind,
      params.language,
      params.visibility,
      params.owner,
      params.ownerUserId,
      params.publicationStatus,
      params.workflowStatus,
      params.moderationStatus,
      params.difficulty,
      params.ratingMin,
      params.rating,
      params.tags,
      params.tag,
      params.includeModeration,
    ],
    queryFn: () =>
      getApiDiscovery(
        params.q,
        params.kind,
        params.scopeKind,
        params.language,
        params.visibility,
        params.owner,
        params.ownerUserId,
        params.publicationStatus,
        params.workflowStatus,
        params.moderationStatus,
        params.difficulty,
        params.ratingMin,
        params.rating,
        params.tags,
        params.tag,
        params.includeModeration,
      ),
    ...options,
  });
}

/** Rate content */
export function usePostApiDiscoveryByKindByIdRatingMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiDiscoveryByKindByIdRating(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Save content preference */
export function usePostApiDiscoveryByKindByIdPreferencesMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiDiscoveryByKindByIdPreferences(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
