// Generated by bunx snapshot sync. Do not edit manually.

import {
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import { postApiGuestSession, deleteApiGuestSession } from "../api/guest";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiGuestSessionResponse,
  JeopardyApiOkResponse,
} from "../types/api";

/** Create guest session */
export function usePostApiGuestSessionMutation(
  options?: UseMutationOptions<
    JeopardyApiGuestSessionResponse,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiGuestSession,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Revoke guest session */
export function useDeleteApiGuestSessionMutation(
  options?: UseMutationOptions<
    JeopardyApiOkResponse,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: deleteApiGuestSession,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
