// Generated by bunx snapshot sync. Do not edit manually.

import {
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  postApiImportsLibraryJson,
  postApiImportsLibraryCsv,
  postApiExportsLibraryByKindByIdJson,
} from "../api/import-export";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Import library JSON */
export function usePostApiImportsLibraryJsonMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiImportsLibraryJson,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Import library CSV */
export function usePostApiImportsLibraryCsvMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiImportsLibraryCsv,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Export library record as JSON */
export function usePostApiExportsLibraryByKindByIdJsonMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiExportsLibraryByKindByIdJson(vars.kind, vars.id),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
