// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  getApiLibraryByKind,
  postApiLibraryByKind,
  getApiLibraryByKindById,
  patchApiLibraryByKindById,
  getApiLibraryByKindByIdVersions,
  postApiLibraryByKindByIdVersions,
  getApiLibraryByKindByIdVersionsByVersionId,
  postApiLibraryByKindByIdSubmit,
  postApiLibraryByKindByIdApprove,
  postApiLibraryByKindByIdReject,
  postApiLibraryByKindByIdPublish,
  postApiLibraryByKindByIdArchive,
} from "../api/library";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** List library records */
export function useGetApiLibraryByKindQuery(
  params: {
    kind: string;
    workflowStatus?: string;
    scopeKind?: string;
    visibility?: string;
    q?: string;
  },
  options?: Omit<
    UseQueryOptions<JeopardyApiItemsResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "library",
      params.kind,
      params.workflowStatus,
      params.scopeKind,
      params.visibility,
      params.q,
    ],
    queryFn: () =>
      getApiLibraryByKind(
        params.kind,
        params.workflowStatus,
        params.scopeKind,
        params.visibility,
        params.q,
      ),
    ...options,
  });
}

/** Create library record */
export function usePostApiLibraryByKindMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiLibraryByKind(vars.kind, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Get library record */
export function useGetApiLibraryByKindByIdQuery(
  params: { kind: string; id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "library", params.kind, params.id],
    queryFn: () => getApiLibraryByKindById(params.kind, params.id),
    ...options,
  });
}

/** Update library record */
export function usePatchApiLibraryByKindByIdMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      patchApiLibraryByKindById(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** List library versions */
export function useGetApiLibraryByKindByIdVersionsQuery(
  params: { kind: string; id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "library", params.kind, params.id, "versions"],
    queryFn: () => getApiLibraryByKindByIdVersions(params.kind, params.id),
    ...options,
  });
}

/** Create library version */
export function usePostApiLibraryByKindByIdVersionsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdVersions(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Get library version */
export function useGetApiLibraryByKindByIdVersionsByVersionIdQuery(
  params: { kind: string; id: string; versionId: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "library",
      params.kind,
      params.id,
      "versions",
      params.versionId,
    ],
    queryFn: () =>
      getApiLibraryByKindByIdVersionsByVersionId(
        params.kind,
        params.id,
        params.versionId,
      ),
    ...options,
  });
}

/** Submit library record */
export function usePostApiLibraryByKindByIdSubmitMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdSubmit(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Approve library record */
export function usePostApiLibraryByKindByIdApproveMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdApprove(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Reject library record */
export function usePostApiLibraryByKindByIdRejectMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdReject(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Publish library record */
export function usePostApiLibraryByKindByIdPublishMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdPublish(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Archive library record */
export function usePostApiLibraryByKindByIdArchiveMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { kind: string; id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiLibraryByKindByIdArchive(vars.kind, vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
