// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  postApiMatchesByIdJoin,
  getApiMatchesByIdAccess,
  postApiMatchesByIdRequestJoin,
  postApiMatchesByIdAccessRequestJoin,
  postApiMatchesByIdApproveByEntryId,
  postApiMatchesByIdAccessApproveByEntryId,
  postApiMatchesByIdWaitlistByEntryIdPromote,
  postApiMatchesByIdReservations,
  postApiMatchesByIdAccessReservations,
  postApiMatchesByIdInvites,
  postApiMatchesByIdAccessInvites,
  postApiMatchesByIdBanByEntryId,
  postApiMatchesByIdAccessBan,
} from "../api/match-access";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** Join match */
export function usePostApiMatchesByIdJoinMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdJoin(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** List match access entries */
export function useGetApiMatchesByIdAccessQuery(
  params: { id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiItemsResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "matches", params.id, "access"],
    queryFn: () => getApiMatchesByIdAccess(params.id),
    ...options,
  });
}

/** Request to join match */
export function usePostApiMatchesByIdRequestJoinMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdRequestJoin(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Request to join match */
export function usePostApiMatchesByIdAccessRequestJoinMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdAccessRequestJoin(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Approve match access entry */
export function usePostApiMatchesByIdApproveByEntryIdMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; entryId: string }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdApproveByEntryId(vars.id, vars.entryId),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Approve match access entry */
export function usePostApiMatchesByIdAccessApproveByEntryIdMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; entryId: string }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdAccessApproveByEntryId(vars.id, vars.entryId),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Promote waitlist entry */
export function usePostApiMatchesByIdWaitlistByEntryIdPromoteMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; entryId: string }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdWaitlistByEntryIdPromote(vars.id, vars.entryId),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create reservation */
export function usePostApiMatchesByIdReservationsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdReservations(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create reservation */
export function usePostApiMatchesByIdAccessReservationsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdAccessReservations(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create invite */
export function usePostApiMatchesByIdInvitesMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdInvites(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create invite */
export function usePostApiMatchesByIdAccessInvitesMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdAccessInvites(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Ban access entry */
export function usePostApiMatchesByIdBanByEntryIdMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; entryId: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) =>
      postApiMatchesByIdBanByEntryId(vars.id, vars.entryId, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Create ban entry */
export function usePostApiMatchesByIdAccessBanMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdAccessBan(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
