// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  getApiMatches,
  postApiMatches,
  getApiMatchesById,
  getApiMatchesByIdState,
  postApiMatchesByIdStart,
  postApiMatchesByIdPause,
  postApiMatchesByIdResume,
  postApiMatchesByIdEnd,
  postApiMatchesByIdEvaluateAnswer,
} from "../api/matches";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** List matches */
export function useGetApiMatchesQuery(
  params: { hostUserId?: string; status?: string; visibility?: string } = {},
  options?: Omit<
    UseQueryOptions<JeopardyApiItemsResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "matches",
      params.hostUserId,
      params.status,
      params.visibility,
    ],
    queryFn: () =>
      getApiMatches(params.hostUserId, params.status, params.visibility),
    ...options,
  });
}

/** Create match */
export function usePostApiMatchesMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiMatches,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Get match */
export function useGetApiMatchesByIdQuery(
  params: { id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "matches", params.id],
    queryFn: () => getApiMatchesById(params.id),
    ...options,
  });
}

/** Get match state */
export function useGetApiMatchesByIdStateQuery(
  params: { id: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "matches", params.id, "state"],
    queryFn: () => getApiMatchesByIdState(params.id),
    ...options,
  });
}

/** Start match */
export function usePostApiMatchesByIdStartMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdStart(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Pause match */
export function usePostApiMatchesByIdPauseMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdPause(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Resume match */
export function usePostApiMatchesByIdResumeMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdResume(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** End match */
export function usePostApiMatchesByIdEndMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdEnd(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Evaluate answer submission */
export function usePostApiMatchesByIdEvaluateAnswerMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiMatchesByIdEvaluateAnswer(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
