// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  getApiMatchesByIdReplay,
  postApiExportsMatchesByIdReplay,
  getApiMatchesByIdExportJson,
} from "../api/match-replay";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiJsonObject,
} from "../types/api";

/** Get match replay */
export function useGetApiMatchesByIdReplayQuery(
  params: { id: string; audience?: string; includeReplay?: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "matches",
      params.id,
      "replay",
      params.audience,
      params.includeReplay,
    ],
    queryFn: () =>
      getApiMatchesByIdReplay(params.id, params.audience, params.includeReplay),
    ...options,
  });
}

/** Export replay payload */
export function usePostApiExportsMatchesByIdReplayMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiExportsMatchesByIdReplay(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** Export match bundle */
export function useGetApiMatchesByIdExportJsonQuery(
  params: { id: string; audience?: string; includeReplay?: string },
  options?: Omit<
    UseQueryOptions<JeopardyApiJsonObject, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: [
      "api",
      "matches",
      params.id,
      "export",
      "json",
      params.audience,
      params.includeReplay,
    ],
    queryFn: () =>
      getApiMatchesByIdExportJson(
        params.id,
        params.audience,
        params.includeReplay,
      ),
    ...options,
  });
}
