// Generated by bunx snapshot sync. Do not edit manually.

import {
  useQuery,
  type UseQueryOptions,
  useMutation,
  useQueryClient,
  type UseMutationOptions,
  type QueryKey,
} from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import {
  postApiModerationReports,
  getApiModerationCases,
  postApiModerationCasesByIdActions,
} from "../api/moderation";
import type {
  JeopardyApiAnyJsonBody,
  JeopardyApiItemsResponse,
  JeopardyApiJsonObject,
} from "../types/api";

/** Create moderation report */
export function usePostApiModerationReportsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    JeopardyApiAnyJsonBody
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: postApiModerationReports,
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}

/** List moderation cases */
export function useGetApiModerationCasesQuery(
  params: { status?: string } = {},
  options?: Omit<
    UseQueryOptions<JeopardyApiItemsResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "moderation", "cases", params.status],
    queryFn: () => getApiModerationCases(params.status),
    ...options,
  });
}

/** Create moderation action */
export function usePostApiModerationCasesByIdActionsMutation(
  options?: UseMutationOptions<
    JeopardyApiJsonObject,
    ApiError,
    { id: string; body: JeopardyApiAnyJsonBody }
  > & { invalidateKeys?: QueryKey[] },
) {
  const { invalidateKeys, ...mutationOptions } = options ?? {};
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars) => postApiModerationCasesByIdActions(vars.id, vars.body),
    ...mutationOptions,
    onSuccess: (...args) => {
      invalidateKeys?.forEach((key) =>
        queryClient.invalidateQueries({ queryKey: key }),
      );
      mutationOptions.onSuccess?.(...args);
    },
  });
}
