// Generated by bunx snapshot sync. Do not edit manually.

import { useQuery, type UseQueryOptions } from "@tanstack/react-query";
import { ApiError } from "@lastshotlabs/snapshot";
import { getApiHealth, getApiReady, getApiJeopardyStatus } from "../api/system";
import type {
  JeopardyApiHealthResponse,
  JeopardyApiReadyResponse,
  JeopardyApiStatusResponse,
} from "../types/api";

/** Health check */
export function useGetApiHealthQuery(
  options?: Omit<
    UseQueryOptions<JeopardyApiHealthResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "health"],
    queryFn: getApiHealth,
    ...options,
  });
}

/** Readiness check */
export function useGetApiReadyQuery(
  options?: Omit<
    UseQueryOptions<JeopardyApiReadyResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "ready"],
    queryFn: getApiReady,
    ...options,
  });
}

/** Runtime status */
export function useGetApiJeopardyStatusQuery(
  options?: Omit<
    UseQueryOptions<JeopardyApiStatusResponse, ApiError>,
    "queryKey" | "queryFn"
  >,
) {
  return useQuery({
    queryKey: ["api", "jeopardy", "status"],
    queryFn: getApiJeopardyStatus,
    ...options,
  });
}
