// snapshot/src/ssr/rsc.ts
// RSC (React Server Components) types and utilities.
// Consumed by renderPage() and the rscTransform() Vite plugin.

// ─── Manifest ─────────────────────────────────────────────────────────────────

/**
 * Maps client component IDs to their output chunk URLs.
 *
 * Generated by the `snapshotSsr()` Vite plugin as `rsc-manifest.json` in the
 * client output directory. The manifest is consumed at runtime by `renderPage()`
 * to resolve client references during the RSC two-pass render.
 *
 * **Key format:** `"{relativePath}#{exportName}"`
 * - `relativePath` — file path relative to the Vite project root, using forward slashes.
 *   Example: `"src/components/Button.tsx"`
 * - `exportName` — the name of the export. Default exports use `"default"`.
 *
 * **Value format:** The hashed chunk URL as it appears in the Vite client manifest.
 * Example: `"assets/Button-Bx2kLm9a.js"`
 *
 * @example
 * ```json
 * {
 *   "components": {
 *     "src/components/Button.tsx#default": "assets/Button-Bx2kLm9a.js",
 *     "src/components/PostCard.tsx#PostCard": "assets/PostCard-Lm9aBx2k.js"
 *   }
 * }
 * ```
 */
export interface RscManifest {
  readonly components: Readonly<Record<string, string>>;
}

// ─── Options ──────────────────────────────────────────────────────────────────

/**
 * Options for RSC-enabled rendering passed to `renderPage()`.
 *
 * When this object is provided, `renderPage()` performs a two-pass RSC render:
 * 1. The React tree is rendered to the RSC flight format using
 *    `react-server-dom-webpack/server`.
 * 2. The RSC flight stream is piped through React DOM server to produce HTML.
 *
 * When omitted, `renderPage()` falls back to the standard single-pass
 * `react-dom/server` render (no RSC).
 */
export interface RscOptions {
  /**
   * The RSC manifest used to resolve client component references during rendering.
   * Load this from `rsc-manifest.json` generated by the `snapshotSsr()` Vite plugin.
   */
  readonly manifest: RscManifest;
}

// ─── Directive detection ──────────────────────────────────────────────────────

/**
 * Returns `true` if the source file contains a `'use client'` or `"use client"`
 * directive as its first meaningful content (before any non-whitespace,
 * non-comment code).
 *
 * The check is intentionally loose — it matches the directive anywhere in the
 * leading whitespace/comment region of the file, consistent with how bundlers
 * like webpack and Parcel handle it.
 *
 * @param code - Raw source text of the file.
 */
export function hasUseClientDirective(code: string): boolean {
  return _hasDirective(code, "use client");
}

/**
 * Returns `true` if the source file contains a `'use server'` or `"use server"`
 * directive as its first meaningful content.
 *
 * @param code - Raw source text of the file.
 */
export function hasUseServerDirective(code: string): boolean {
  return _hasDirective(code, "use server");
}

/**
 * Scan the leading lines of `code` for a directive string.
 * Stops as soon as a non-comment, non-whitespace, non-directive line is found.
 *
 * @internal
 */
function _hasDirective(code: string, directive: string): boolean {
  const lines = code.split("\n");
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line === "") continue;
    // Single-line comments — keep scanning.
    if (line.startsWith("//")) continue;
    // Block comment open — keep scanning (simplified: skip entire line).
    if (line.startsWith("/*") || line.startsWith("*")) continue;
    // Directive match.
    if (line === `'${directive}'` || line === `'${directive}';`) return true;
    if (line === `"${directive}"` || line === `"${directive}";`) return true;
    // First non-comment, non-blank, non-directive line — no directive found.
    return false;
  }
  return false;
}

// ─── Component ID ─────────────────────────────────────────────────────────────

/**
 * Builds the component ID string used as a key in {@link RscManifest.components}.
 *
 * Format: `"{relativePath}#{exportName}"`
 *
 * @param relativePath - File path relative to the Vite project root, forward-slash
 *   separated. Example: `"src/components/Button.tsx"`.
 * @param exportName - Export name. Use `"default"` for default exports.
 *
 * @example
 * ```ts
 * buildComponentId('src/components/Button.tsx', 'default');
 * // → 'src/components/Button.tsx#default'
 *
 * buildComponentId('src/components/Button.tsx', 'Button');
 * // → 'src/components/Button.tsx#Button'
 * ```
 */
export function buildComponentId(
  relativePath: string,
  exportName: string,
): string {
  return `${relativePath}#${exportName}`;
}
