import { describe, it, expect, beforeEach, afterEach } from "vitest";
import path from "node:path";
import fs from "node:fs/promises";
import os from "node:os";

describe("manifest processing", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(
      path.join(os.tmpdir(), "snapshot-manifest-test-"),
    );
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  // ── readManifest ──────────────────────────────────────────────────────────

  describe("readManifest", () => {
    it("returns null for missing file", async () => {
      const { readManifest } = await import("../sync");
      const result = await readManifest(tmpDir);
      expect(result).toBeNull();
    });

    it("returns config for valid manifest", async () => {
      const { readManifest } = await import("../sync");
      const manifest = {
        pages: {
          "/": {
            title: "Home",
            content: [{ type: "heading", text: "Hello" }],
          },
        },
      };
      await fs.writeFile(
        path.join(tmpDir, "snapshot.manifest.json"),
        JSON.stringify(manifest),
        "utf8",
      );
      const result = await readManifest(tmpDir);
      expect(result).not.toBeNull();
      const rootPage = result!.pages["/"];
      expect(rootPage).toBeDefined();
      expect(rootPage!.title).toBe("Home");
    });

    it("throws for invalid manifest", async () => {
      const { readManifest } = await import("../sync");
      const invalid = { pages: "not-an-object" };
      await fs.writeFile(
        path.join(tmpDir, "snapshot.manifest.json"),
        JSON.stringify(invalid),
        "utf8",
      );
      await expect(readManifest(tmpDir)).rejects.toThrow(
        "Invalid snapshot.manifest.json",
      );
    });
  });

  // ── generateThemeCss ──────────────────────────────────────────────────────

  describe("generateThemeCss", () => {
    it("produces CSS with custom properties", async () => {
      const { generateThemeCss } = await import("../sync");
      const css = generateThemeCss({
        flavor: "neutral",
        overrides: {
          colors: {
            primary: "#3b82f6",
          },
        },
      });
      expect(css).toContain(":root");
      expect(css).toContain("--primary");
      expect(css).toContain(".dark");
    });

    it("produces CSS with default flavor when no overrides", async () => {
      const { generateThemeCss } = await import("../sync");
      const css = generateThemeCss({});
      expect(css).toContain(":root");
      expect(css).toContain("--radius");
      expect(css).toContain("--spacing-unit");
    });
  });

  // ── generateRouteFile ─────────────────────────────────────────────────────

  describe("generateRouteFile", () => {
    it("produces valid route code with imports", async () => {
      const { generateRouteFile } = await import("../sync");
      const page = {
        title: "Dashboard",
        content: [{ type: "heading", text: "Dashboard" }],
      };
      const code = generateRouteFile("/dashboard", page);

      expect(code).toContain(
        "// This file is auto-generated by snapshot sync. Do not edit.",
      );
      expect(code).toContain(
        "import { createFileRoute } from '@tanstack/react-router'",
      );
      expect(code).toContain(
        "import { PageRenderer } from '@lastshotlabs/snapshot/ui'",
      );
      expect(code).toContain("createFileRoute('/dashboard')");
      expect(code).toContain("PageRenderer");
      expect(code).toContain('"title": "Dashboard"');
    });

    it("handles root path", async () => {
      const { generateRouteFile } = await import("../sync");
      const page = {
        content: [{ type: "heading", text: "Home" }],
      };
      const code = generateRouteFile("/", page);
      expect(code).toContain("createFileRoute('/')");
    });
  });

  // ── generateNavFile ───────────────────────────────────────────────────────

  describe("generateNavFile", () => {
    it("produces nav component code", async () => {
      const { generateNavFile } = await import("../sync");
      const nav = [
        { label: "Home", path: "/" },
        { label: "Settings", path: "/settings", icon: "settings" },
        {
          label: "Admin",
          path: "/admin",
          children: [{ label: "Users", path: "/admin/users" }],
        },
      ];
      const code = generateNavFile(nav);

      expect(code).toContain(
        "// This file is auto-generated by snapshot sync. Do not edit.",
      );
      expect(code).toContain("import { Link } from '@tanstack/react-router'");
      expect(code).toContain("export function Nav()");
      expect(code).toContain('data-snapshot-component="nav"');
      expect(code).toContain('"label": "Home"');
      expect(code).toContain('"label": "Admin"');
      expect(code).toContain('"label": "Users"');
    });
  });
});
