// Generated by bunx snapshot sync. Do not edit manually.

export interface JeopardyApiHealthResponse {
  ok: boolean;
  app: string;
}

export interface JeopardyApiReadyResponse {
  ok: boolean;
  ready: boolean;
}

export interface JeopardyApiStatusResponse {
  ok: boolean;
  gameType: string;
  phase: string;
}

export interface JeopardyApiGuestSessionResponse {
  guest: {
    userId: string;
    displayName: string;
    expiresAt: string;
  };
  session: JeopardyApiJsonObject;
}

export interface JeopardyApiJsonObject extends Record<string, unknown> {}

export interface JeopardyApiErrorResponse {
  error: string;
}

export interface JeopardyApiAnyJsonBody extends Record<string, unknown> {}

export interface JeopardyApiOkResponse {
  ok: boolean;
}

export interface JeopardyApiItemsResponse {
  items: JeopardyApiJsonObject[];
}
