/**
 * @lastshotlabs/snapshot/ui
 *
 * Config-driven UI entry point. Everything needed to build applications
 * from a JSON manifest — components, tokens, flavors, page rendering,
 * context system, actions, and headless hooks.
 *
 * SDK consumers who write their own React import from '@lastshotlabs/snapshot'.
 * Config-driven consumers import from '@lastshotlabs/snapshot/ui'.
 */
export { resolveTokens, resolveFrameworkStyles } from "./ui/tokens/resolve";
export { validateContrast } from "./ui/tokens/contrast-checker";
export { useTokenEditor } from "./ui/tokens/editor";
export { defineFlavor, getFlavor, getAllFlavors } from "./ui/tokens/flavors";
export { themeColorsSchema, radiusSchema, spacingSchema, fontSchema, componentTokensSchema, themeConfigSchema, } from "./ui/tokens/schema";
export { hexToOklch, hslToOklch, oklchToString, oklchToHex, deriveForeground, deriveDarkVariant, colorToOklch, parseOklchString, relativeLuminance, contrastRatio, meetsWcagAA, } from "./ui/tokens/color";
export type { ThemeConfig, ThemeColors, Flavor, ComponentTokens, TokenEditor, RadiusScale, SpacingScale, FontConfig, Responsive, } from "./ui/tokens/types";
export { registerAnalyticsProvider } from "./ui/analytics/registry";
export { registerClient, getRegisteredClient } from "./api/client";
export type { AnalyticsProvider, AnalyticsProviderFactory, AnalyticsProviderInitConfig, } from "./ui/analytics/types";
export { PageContextProvider, AppContextProvider, usePublish, useSubscribe, useResolveFrom, isFromRef, } from "./ui/context/index";
export type { ExprRef, FromRef, AtomRegistry, GlobalConfig, AppContextProviderProps, PageContextProviderProps, ResolvedConfig, } from "./ui/context/types";
export { useStateValue, useSetStateValue, useResetStateValue, useApiClient, } from "./ui/state/index";
export type { StateScope, StateHookScope, StateConfig as RuntimeStateConfig, StateConfigMap, StateProviderProps, } from "./ui/state/index";
export { useActionExecutor, SnapshotApiContext, useModalManager, useToastManager, ToastContainer, useConfirmManager, ConfirmDialog, interpolate, actionSchema, navigateActionSchema, apiActionSchema, openModalActionSchema, closeModalActionSchema, refreshActionSchema, setValueActionSchema, downloadActionSchema, copyToClipboardActionSchema, confirmActionSchema, scrollToActionSchema, toastActionSchema, trackActionSchema, runWorkflowActionSchema, debounceAction, throttleAction, } from "./ui/actions/index";
export type { ActionConfig, ActionExecuteFn, ActionBase, NavigateAction, ApiAction, OpenModalAction, CloseModalAction, RefreshAction, SetValueAction, DownloadAction, CopyAction, CopyToClipboardAction, ConfirmAction, ScrollToAction, ToastAction, LogAction, TrackAction, RunWorkflowAction, ModalManager, ToastItem, ShowToastOptions, ToastManager, ConfirmRequest, ConfirmOptions, ConfirmManager, } from "./ui/actions/index";
export { StatCard, statCardConfigSchema, trendConfigSchema, } from "./ui/components/data/stat-card/index";
export type { StatCardConfig, UseStatCardResult, } from "./ui/components/data/stat-card/index";
export { useComponentData } from "./ui/components/_base/use-component-data";
export type { ComponentDataResult } from "./ui/components/_base/use-component-data";
export { registerBuiltInComponents, resetBuiltInComponentRegistration, } from "./ui/components/register";
export { ManifestApp, PageRenderer, ComponentRenderer, bootBuiltins, resetBootBuiltins, TransitionWrapper, compileManifest, defineManifest, parseManifest, buildRequestUrl, dataSourceSchema, endpointTargetSchema, httpMethodSchema, isResourceRef, runWorkflow, registerComponent, registerComponentSchema, registerLayout, resolveLayout, getRegisteredLayouts, registerGuard, resolveGuard, getRegisteredGuards, registerWorkflowAction, getRegisteredWorkflowAction, getRegisteredSchemaTypes, injectStyleSheet, generateJsonSchema, ManifestRuntimeProvider, OverlayRuntimeProvider, RouteRuntimeProvider, useManifestResourceFocusRefetch, useManifestResourceMountRefetch, useManifestRuntime, useManifestResourceCache, useOverlayRuntime, useRouteRuntime, useRoutePrefetch, useVirtualList, manifestConfigSchema, appConfigSchema, toastConfigSchema, analyticsConfigSchema, analyticsProviderSchema, pushConfigSchema, pageConfigSchema, routeGuardConfigSchema, routeGuardSchema, routeTransitionSchema, routeConfigSchema, outletComponentSchema, overlayConfigSchema, componentConfigSchema, navItemSchema, navigationConfigSchema, authScreenConfigSchema, authProviderSchema, resourceConfigSchema, resourceRefSchema, stateValueConfigSchema, workflowConditionSchema, workflowDefinitionSchema, workflowNodeSchema, baseComponentConfigSchema, rowConfigSchema, headingConfigSchema, buttonConfigSchema, selectConfigSchema, cardConfigSchema, componentsConfigSchema, customComponentDeclarationSchema, customComponentPropSchema, fromRefSchema, } from "./ui/manifest/index";
export type { AppConfig, ToastConfig, AnalyticsConfig, PushConfig, CompiledManifest, CompiledRoute, RouteMatch, ManifestConfig, NavItem, NavigationConfig, AuthScreenConfig, AuthProviderConfig, PageConfig, RouteGuard, RouteGuardConfig, RouteConfig, ResourceConfigMap, OverlayConfig, AssignWorkflowNode, CaptureWorkflowNode, ParallelWorkflowNode, RetryWorkflowNode, TryWorkflowNode, WaitWorkflowNode, WorkflowCondition, WorkflowConditionOperator, WorkflowDefinition, WorkflowMap, WorkflowNode, IfWorkflowNode, WorkflowActionHandler, StateConfig, StateValueConfig, BaseComponentConfig, RowConfig, HeadingConfig, ButtonConfig, SelectConfig, CardConfig, OutletConfig, ComponentConfig, ManifestAppProps, ConfigDrivenComponent, ComponentRendererProps, PageRendererProps, } from "./ui/manifest/index";
export { Layout, layoutConfigSchema, } from "./ui/components/layout/layout/index";
export type { LayoutConfig, LayoutProps, LayoutVariant, } from "./ui/components/layout/layout/index";
export { Nav, navConfigSchema, useNav } from "./ui/components/layout/nav/index";
export type { NavConfig, NavItemConfig, ResolvedNavItem, UseNavResult, } from "./ui/components/layout/nav/index";
export { Card } from "./ui/components/layout/card/index";
export { Column, columnConfigSchema as layoutColumnConfigSchema, } from "./ui/components/layout/column/index";
export type { ColumnConfig as LayoutColumnConfig } from "./ui/components/layout/column/index";
export { Outlet } from "./ui/components/layout/outlet/index";
export { DataTable } from "./ui/components/data/data-table/index";
export { dataTableConfigSchema, columnConfigSchema, rowActionSchema, bulkActionSchema, } from "./ui/components/data/data-table/schema";
export { useDataTable } from "./ui/components/data/data-table/hook";
export type { DataTableConfig, ColumnConfig, RowAction, BulkAction, SortState, PaginationState, ResolvedColumn, UseDataTableResult, } from "./ui/components/data/data-table/types";
export { DetailCard } from "./ui/components/data/detail-card/index";
export { detailCardConfigSchema } from "./ui/components/data/detail-card/schema";
export { useDetailCard } from "./ui/components/data/detail-card/hook";
export type { DetailCardConfig, UseDetailCardResult, } from "./ui/components/data/detail-card/types";
export { AutoForm } from "./ui/components/forms/auto-form/index";
export { autoFormConfigSchema, fieldConfigSchema, } from "./ui/components/forms/auto-form/schema";
export { useAutoForm } from "./ui/components/forms/auto-form/hook";
export type { AutoFormConfig, FieldConfig, FieldErrors, TouchedFields, UseAutoFormResult, } from "./ui/components/forms/auto-form/types";
export { ModalComponent, modalConfigSchema, } from "./ui/components/overlay/modal";
export type { ModalConfig } from "./ui/components/overlay/modal";
export { DrawerComponent, drawerConfigSchema, } from "./ui/components/overlay/drawer";
export type { DrawerConfig } from "./ui/components/overlay/drawer";
export { TabsComponent, tabsConfigSchema, tabConfigSchema, } from "./ui/components/navigation/tabs";
export type { TabsConfig, TabConfig } from "./ui/components/navigation/tabs";
export { PrefetchLink, prefetchLinkSchema, } from "./ui/components/navigation/prefetch-link/index";
export type { PrefetchLinkConfig } from "./ui/components/navigation/prefetch-link/index";
export { RichTextEditor, richTextEditorConfigSchema, } from "./ui/components/content/rich-text-editor/index";
export type { RichTextEditorConfig } from "./ui/components/content/rich-text-editor/index";
export { Heading } from "./ui/components/content/heading/index";
export { Code, codeConfigSchema } from "./ui/components/content/code/index";
export type { CodeConfig } from "./ui/components/content/code/index";
export { RichInput, richInputConfigSchema, } from "./ui/components/content/rich-input/index";
export type { RichInputConfig } from "./ui/components/content/rich-input/index";
export { EmojiPicker, emojiPickerConfigSchema, } from "./ui/components/communication/emoji-picker/index";
export type { EmojiPickerConfig } from "./ui/components/communication/emoji-picker/index";
export { ReactionBar, reactionBarConfigSchema, } from "./ui/components/communication/reaction-bar/index";
export type { ReactionBarConfig } from "./ui/components/communication/reaction-bar/index";
export { PresenceIndicator, presenceIndicatorConfigSchema, } from "./ui/components/communication/presence-indicator/index";
export type { PresenceIndicatorConfig } from "./ui/components/communication/presence-indicator/index";
export { TypingIndicator, typingIndicatorConfigSchema, } from "./ui/components/communication/typing-indicator/index";
export type { TypingIndicatorConfig } from "./ui/components/communication/typing-indicator/index";
export { MessageThread, messageThreadConfigSchema, } from "./ui/components/communication/message-thread/index";
export type { MessageThreadConfig } from "./ui/components/communication/message-thread/index";
export { CommentSection, commentSectionConfigSchema, } from "./ui/components/communication/comment-section/index";
export type { CommentSectionConfig } from "./ui/components/communication/comment-section/index";
export { ChatWindow, chatWindowConfigSchema, } from "./ui/components/communication/chat-window/index";
export type { ChatWindowConfig } from "./ui/components/communication/chat-window/index";
export { Popover, popoverConfigSchema, } from "./ui/components/overlay/popover/index";
export type { PopoverConfig } from "./ui/components/overlay/popover/index";
export { Separator, separatorConfigSchema, } from "./ui/components/data/separator/index";
export type { SeparatorConfig } from "./ui/components/data/separator/index";
export { CommandPalette, commandPaletteConfigSchema, } from "./ui/components/overlay/command-palette/index";
export type { CommandPaletteConfig } from "./ui/components/overlay/command-palette/index";
export { Input, inputConfigSchema } from "./ui/components/forms/input/index";
export type { InputConfig } from "./ui/components/forms/input/index";
export { Select } from "./ui/components/forms/select/index";
export { DatePicker, datePickerConfigSchema, } from "./ui/components/forms/date-picker";
export type { DatePickerConfig } from "./ui/components/forms/date-picker";
export { Slider, sliderConfigSchema } from "./ui/components/forms/slider";
export type { SliderConfig } from "./ui/components/forms/slider";
export { ColorPicker, colorPickerConfigSchema, } from "./ui/components/forms/color-picker";
export type { ColorPickerConfig } from "./ui/components/forms/color-picker";
export { Textarea, textareaConfigSchema, } from "./ui/components/forms/textarea/index";
export type { TextareaConfig } from "./ui/components/forms/textarea/index";
export { Toggle, toggleConfigSchema } from "./ui/components/forms/toggle/index";
export type { ToggleConfig } from "./ui/components/forms/toggle/index";
export { MultiSelect, multiSelectConfigSchema, } from "./ui/components/forms/multi-select/index";
export type { MultiSelectConfig } from "./ui/components/forms/multi-select/index";
export { ContextMenu, contextMenuConfigSchema, } from "./ui/components/overlay/context-menu/index";
export type { ContextMenuConfig } from "./ui/components/overlay/context-menu/index";
export { ConfirmDialogComponent, confirmDialogConfigSchema, } from "./ui/components/overlay/confirm-dialog/index";
export type { ConfirmDialogConfig } from "./ui/components/overlay/confirm-dialog/index";
export { ScrollArea, scrollAreaConfigSchema, } from "./ui/components/data/scroll-area/index";
export type { ScrollAreaConfig } from "./ui/components/data/scroll-area/index";
export { FilterBar, filterBarConfigSchema, } from "./ui/components/data/filter-bar/index";
export type { FilterBarConfig } from "./ui/components/data/filter-bar/index";
export { InlineEdit, inlineEditConfigSchema, } from "./ui/components/forms/inline-edit/index";
export type { InlineEditConfig } from "./ui/components/forms/inline-edit/index";
export { Markdown, markdownConfigSchema, } from "./ui/components/content/markdown/index";
export type { MarkdownConfig } from "./ui/components/content/markdown/index";
export { TagSelector, tagSelectorConfigSchema, } from "./ui/components/forms/tag-selector/index";
export type { TagSelectorConfig } from "./ui/components/forms/tag-selector/index";
export { EntityPicker, entityPickerConfigSchema, } from "./ui/components/data/entity-picker/index";
export type { EntityPickerConfig } from "./ui/components/data/entity-picker/index";
export { HighlightedText, highlightedTextConfigSchema, } from "./ui/components/data/highlighted-text/index";
export type { HighlightedTextConfig } from "./ui/components/data/highlighted-text/index";
export { FavoriteButton, favoriteButtonConfigSchema, } from "./ui/components/data/favorite-button/index";
export type { FavoriteButtonConfig } from "./ui/components/data/favorite-button/index";
export { NotificationBell, notificationBellConfigSchema, } from "./ui/components/data/notification-bell/index";
export type { NotificationBellConfig } from "./ui/components/data/notification-bell/index";
export { SaveIndicator, saveIndicatorConfigSchema, } from "./ui/components/data/save-indicator/index";
export type { SaveIndicatorConfig } from "./ui/components/data/save-indicator/index";
export { CompareView, compareViewConfigSchema, } from "./ui/components/content/compare-view/index";
export type { CompareViewConfig } from "./ui/components/content/compare-view/index";
export { QuickAdd, quickAddConfigSchema, } from "./ui/components/forms/quick-add/index";
export type { QuickAddConfig } from "./ui/components/forms/quick-add/index";
export { LocationInput, locationInputConfigSchema, } from "./ui/components/forms/location-input/index";
export type { LocationInputConfig } from "./ui/components/forms/location-input/index";
export { AvatarGroup, avatarGroupConfigSchema, } from "./ui/components/data/avatar-group/index";
export type { AvatarGroupConfig } from "./ui/components/data/avatar-group/index";
export { LinkEmbed, linkEmbedConfigSchema, detectPlatform, PLATFORM_COLORS, PLATFORM_NAMES, } from "./ui/components/content/link-embed/index";
export type { LinkEmbedConfig, Platform, PlatformInfo, } from "./ui/components/content/link-embed/index";
export { GifPicker, gifPickerConfigSchema, } from "./ui/components/communication/gif-picker/index";
export type { GifPickerConfig, GifEntry, } from "./ui/components/communication/gif-picker/index";
export { Feed, feedSchema } from "./ui/components/data/feed/index";
export type { FeedConfig, FeedItem, UseFeedResult, } from "./ui/components/data/feed/types";
export { Chart, chartSchema, seriesConfigSchema, } from "./ui/components/data/chart/index";
export type { ChartConfig, SeriesConfig, } from "./ui/components/data/chart/types";
export { Wizard, wizardSchema, wizardStepSchema, useWizard, } from "./ui/components/forms/wizard/index";
export type { WizardConfig, WizardStepConfig, UseWizardResult, } from "./ui/components/forms/wizard/types";
export { parseShortcodes, buildEmojiMap, resolveEmojiRecords, CUSTOM_EMOJI_CSS, } from "./ui/components/communication/emoji-picker/index";
export type { CustomEmoji } from "./ui/components/communication/emoji-picker/index";
export { Icon, ICON_PATHS } from "./ui/icons/index";
export type { IconProps } from "./ui/icons/index";
export { authPage, crudPage, dashboardPage, expandPreset, settingsPage, authPresetConfigSchema, crudPresetConfigSchema, dashboardPresetConfigSchema, settingsPresetConfigSchema, } from "./ui/presets/index";
export type { ActivityFeedDef, AuthBrandingDef, AuthPageOptions, ChartDef, CrudPageOptions, DashboardPageOptions, EmptyStateDef, PaginationDef, SettingsPageOptions, ColumnDef, FormDef, FormFieldDef, FormFieldOption, FilterDef, FilterOption, StatDef, SettingsSectionDef, } from "./ui/presets/types";
export { useUrlSync } from "./ui/hooks/use-url-sync";
export { clearPersistedState, readPersistedState, toPersistedStateKey, writePersistedState, } from "./ui/state/persist";
export { usePersistedAtom } from "./ui/state/use-persisted-atom";
export { SnapshotImage, snapshotImageSchema, } from "./ui/components/media/image/index";
export type { SnapshotImageConfig } from "./ui/components/media/image/index";
export { DndContext, SortableContext, DragOverlay, closestCenter, useSortable, verticalListSortingStrategy, horizontalListSortingStrategy, arrayMove, useDndSensors, getSortableStyle, PointerSensor, KeyboardSensor, CSS as DndCSS, } from "./ui/hooks/use-drag-drop";
export type { DragStartEvent, DragEndEvent, DragOverEvent, } from "./ui/hooks/use-drag-drop";
export { useBreakpoint, useResponsiveValue, resolveResponsiveValue, BREAKPOINTS as UI_BREAKPOINTS, } from "./ui/hooks/use-breakpoint";
export type { Breakpoint } from "./ui/hooks/use-breakpoint";
export { usePoll } from "./ui/hooks/use-poll";
export type { UsePollOptions } from "./ui/hooks/use-poll";
export { useInfiniteScroll } from "./ui/hooks/use-infinite-scroll";
export type { UseInfiniteScrollOptions } from "./ui/hooks/use-infinite-scroll";
export { useAutoBreadcrumbs } from "./ui/hooks/use-auto-breadcrumbs";
export { generateBreadcrumbs, type BreadcrumbAutoConfig, type BreadcrumbItem, } from "./ui/manifest/breadcrumbs";
