import { writeFileSync } from "node:fs";
import path from "node:path";
import {
  collectComponentDirectories,
  type ComponentDirectoryRecord,
} from "../docs/component-inventory.ts";
import { ensureDir, repoPath } from "../docs/_common.ts";

function toPascalCase(value: string): string {
  const words = value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  const candidate = words
    .map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`)
    .join("");

  return /^[0-9]/.test(candidate) ? `Component${candidate}` : candidate;
}

function uniqueStoryName(
  component: ComponentDirectoryRecord,
  used: Set<string>,
): string {
  const base = toPascalCase(component.componentName);
  if (!used.has(base)) {
    used.add(base);
    return base;
  }

  const withDomain = `${toPascalCase(component.domain)}${base}`;
  if (!used.has(withDomain)) {
    used.add(withDomain);
    return withDomain;
  }

  let index = 2;
  while (used.has(`${withDomain}${index}`)) {
    index += 1;
  }

  const name = `${withDomain}${index}`;
  used.add(name);
  return name;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

const components = collectComponentDirectories().filter(
  (component) => component.hasComponent,
);
const usedStoryNames = new Set<string>();
const storyRecords = components.map((component) => ({
  ...component,
  storyName: uniqueStoryName(component, usedStoryNames),
}));

const outputFile = repoPath(
  "src",
  "ui",
  "components",
  "__stories__",
  "generated-components.stories.tsx",
);

const lines: string[] = [];
lines.push("/* This file is generated by scripts/storybook/generate-component-stories.ts. */");
lines.push("/* Do not edit manually. */");
lines.push("");
lines.push("import type { Meta, StoryObj } from \"@storybook/react-vite\";");
lines.push("");
lines.push("const COMPONENTS = [");
for (const component of storyRecords) {
  lines.push(
    `  { name: ${quote(component.componentName)}, domain: ${quote(component.domain)}, path: ${quote(component.relativeDir)} },`,
  );
}
lines.push("] as const;");
lines.push("");
lines.push("function ComponentCatalog({ selected }: { selected?: string }) {");
lines.push("  const visible = selected");
lines.push("    ? COMPONENTS.filter((component) => component.name === selected)");
lines.push("    : COMPONENTS;");
lines.push("");
lines.push("  return (");
lines.push("    <main style={{ fontFamily: \"system-ui, sans-serif\", padding: 24 }}>");
lines.push("      <h1>Snapshot Components</h1>");
lines.push("      <p>Generated inventory of code-first UI component directories.</p>");
lines.push("      <ul>");
lines.push("        {visible.map((component) => (");
lines.push("          <li key={component.path}>");
lines.push("            <strong>{component.name}</strong>");
lines.push("            {\" \"}");
lines.push("            <span style={{ color: \"#64748b\" }}>{component.domain}</span>");
lines.push("          </li>");
lines.push("        ))}");
lines.push("      </ul>");
lines.push("    </main>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("const meta = {");
lines.push("  title: \"Snapshot/Generated Components\",");
lines.push("  component: ComponentCatalog,");
lines.push("  parameters: { controls: { expanded: true } },");
lines.push("} satisfies Meta<typeof ComponentCatalog>;");
lines.push("");
lines.push("export default meta;");
lines.push("");
lines.push("type Story = StoryObj<typeof meta>;");
lines.push("");
lines.push("export const AllComponents: Story = {");
lines.push("  args: {},");
lines.push("};");
lines.push("");

for (const component of storyRecords) {
  lines.push(`export const ${component.storyName}: Story = {`);
  lines.push(`  name: ${quote(component.componentName)},`);
  lines.push(`  args: { selected: ${quote(component.componentName)} },`);
  lines.push("};");
  lines.push("");
}

ensureDir(outputFile);
writeFileSync(outputFile, `${lines.join("\n").trim()}\n`, "utf8");

const relativeOutput = path.relative(repoPath(), outputFile).replace(/\\/g, "/");
console.log(
  `[storybook:generate] Wrote ${storyRecords.length} component inventory stories to ${relativeOutput}.`,
);
